# -*- coding: utf-8 -*-
"""monitor_xyzverse.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tF2P0y9RMzFyWq_9MCwmzX4x3ZqqFhIQ
"""

import requests
from bs4 import BeautifulSoup
from datetime import datetime, timedelta
import smtplib
from email.mime.text import MIMEText
import os

def get_xyzverse_data():
    url = "https://xyzverse.io/pt"
    r = requests.get(url)
    soup = BeautifulSoup(r.text, "html.parser")

    current = soup.select_one(".Cards_amount__XRyyb.Cards_number__tCA2G").text
    goal = soup.select_one(".Cards_gray__b1UW2.Cards_small__6NNSv").text.replace(" / ","")

    current_val = float(current.replace("$","").replace(",",""))
    goal_val = float(goal.replace("$","").replace(",",""))
    percent = round((current_val/goal_val)*100,2)

    current_price = soup.select_one(".Cards_number__tCA2G").text
    next_price = soup.select_one("div:has-text('Próximo Preço') span").text

    timestamp = (datetime.utcnow() - timedelta(hours=3)).strftime("%d/%m/%Y %H:%M")

    message = f"{timestamp}\nCaptação: ${current_val} / ${goal_val} ({percent}%)\nPreço atual: {current_price}\nPróximo preço: {next_price}"
    return message

def send_email(message):
    sender = os.environ['EMAIL_USER']
    password = os.environ['EMAIL_PASS']
    receiver = sender

    msg = MIMEText(message)
    msg['Subject'] = "Atualização XYZVerse"
    msg['From'] = sender
    msg['To'] = receiver

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(sender, password)
        server.send_message(msg)

if __name__ == "__main__":
    email_text = get_xyzverse_data()
    send_email(email_text)
    print(email_text)
